# Generated by Django 4.2.23 on 2025-08-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='dispatcher',
        ),
    ]
