# Generated by Django 4.2.23 on 2025-08-07 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinout',
            name='user',
        ),
        migrations.AddField(
            model_name='checkinout',
            name='driver',
            field=models.ForeignKey(default=0, limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_outs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
