# Generated by Django 4.2.23 on 2025-08-07 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_load_dispatcher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='unassigned', max_length=20)),
                ('dispatcher', models.ForeignKey(limit_choices_to={'user_type': 'dispatcher'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_assignments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='app.load')),
            ],
        ),
    ]
