# Generated by Django 4.2.23 on 2025-08-07 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dispatcher',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'dispatcher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatcher_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
