# Generated by Django 4.2.23 on 2025-08-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.FileField(blank=True, null=True, upload_to='Profile/'),
        ),
    ]
